---
galaxy_info:
  author: Niccolo
  description: Apache ZooKeeper installation for SigNoz stack
  license: proprietary
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []